In [1]:
#Import numpy as np
import numpy as np

In [5]:
#Print the numpy version
z = np.__version__
print(z)

1.23.5


In [6]:
#Create a null verctor of size 10
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
#find the memory size of the array
z = np.array([2,3,4,5,6])
arr = z.nbytes
print(arr)

40


In [9]:
#Create a null vector of size 10
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
#Crete a vector at value 5
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
#create a vector with values ranging from 10 to 40.
a = np.arange(10, 50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [15]:
#range vector
np.arange(1, 20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [21]:
#Reverse a vector
a = np.arange(50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [20]:
#create a 3x3 matrix with values raging from 0 to 8
a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [25]:
a = np.zeros([2,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
np.nonzero([2,1,4,5,0,0,4,5,6])

(array([0, 1, 2, 3, 6, 7, 8]),)

In [27]:
#create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
#create a 3x3x3 matrx

np.random.random([3,3,3])

array([[[0.76956313, 0.16662465, 0.71351165],
        [0.37864082, 0.24348701, 0.2581135 ],
        [0.44975147, 0.48854245, 0.52470501]],

       [[0.12472293, 0.44161435, 0.53876727],
        [0.26242497, 0.6507805 , 0.25735803],
        [0.86561795, 0.30855982, 0.57143946]],

       [[0.37147759, 0.02980467, 0.29478947],
        [0.84386956, 0.92383741, 0.54830527],
        [0.87745356, 0.74107616, 0.66880761]]])

In [40]:
#create a random vector of size 30 and find the mean value
z = np.random.random(30)
m = z.mean()
print(m)

0.4202077531469778


In [44]:
#create a random array of 10x10 find min and max
z = np.random.random((10,10))
print(z)

[[0.18628901 0.9854849  0.57409587 0.43252359 0.34458539 0.05635957
  0.99484306 0.11377084 0.62271795 0.02971755]
 [0.84836029 0.45543201 0.90266667 0.83914103 0.63640089 0.31040397
  0.50141273 0.13478669 0.16738098 0.68761822]
 [0.14828357 0.89731387 0.85688552 0.3719784  0.48796014 0.19279291
  0.40152041 0.53264013 0.05332953 0.71837959]
 [0.33023703 0.32942752 0.45402285 0.76888661 0.51587065 0.17296301
  0.12920232 0.40327349 0.15766838 0.55796653]
 [0.72644537 0.0709016  0.87935853 0.35285003 0.70591591 0.55968378
  0.38227921 0.17893425 0.02220978 0.20936329]
 [0.49357356 0.45643943 0.79754944 0.58391199 0.30954966 0.79987435
  0.700617   0.58614387 0.40207982 0.72521054]
 [0.21737954 0.86639371 0.9238788  0.1074335  0.78992346 0.59610587
  0.82935626 0.1477509  0.86948345 0.6203859 ]
 [0.88266893 0.83399682 0.97183999 0.91292907 0.64636976 0.39042331
  0.1352246  0.86020553 0.30873123 0.52412298]
 [0.76731582 0.76480369 0.50960368 0.58105525 0.96828958 0.56651885
  0.17516001

In [47]:
# find the min and max
zmin, zmax = z.min(), z.max()
print(zmin, zmax)

0.022209782782297127 0.9948430556716906


In [49]:
#create a random vector of size 30 and find mean
z = np.random.random(30)
mean = z.mean()
print(mean)

0.5511968095362064


In [50]:
#create a 1d array
z = np.array([2,3,4,5,8])
print(z)

[2 3 4 5 8]


In [52]:
#create a 2d array
z = np.array([[2,3,4], [7,5,8]])
print(z)

[[2 3 4]
 [7 5 8]]


In [55]:
#create a 3d array
z = np.array([[[2,3,4], [7,5,8]],
             [[5,4,6], [4,7,8]]])
print(z)

#Two 2d arrays makes a 3D array

[[[2 3 4]
  [7 5 8]]

 [[5 4 6]
  [4 7 8]]]


In [59]:
z = np.ones((10,10))
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [63]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan) #nan is not a number, inf is infinity
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


In [72]:
np.diag(1+np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [77]:
#create a 8x8 matrix
np.zeros((8,8), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])