In [1]:
#Import numpy as np
import numpy as np

In [5]:
#Print the numpy version
z = np.__version__
print(z)

1.23.5


In [6]:
#Create a null verctor of size 10
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
#find the memory size of the array
z = np.array([2,3,4,5,6])
arr = z.nbytes
print(arr)

40


In [9]:
#Create a null vector of size 10
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
#Crete a vector at value 5
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
#create a vector with values ranging from 10 to 40.
a = np.arange(10, 50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [15]:
#range vector
np.arange(1, 20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [21]:
#Reverse a vector
a = np.arange(50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [20]:
#create a 3x3 matrix with values raging from 0 to 8
a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [25]:
a = np.zeros([2,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
np.nonzero([2,1,4,5,0,0,4,5,6])

(array([0, 1, 2, 3, 6, 7, 8]),)

In [27]:
#create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
#create a 3x3x3 matrx

np.random.random([3,3,3])

array([[[0.76956313, 0.16662465, 0.71351165],
        [0.37864082, 0.24348701, 0.2581135 ],
        [0.44975147, 0.48854245, 0.52470501]],

       [[0.12472293, 0.44161435, 0.53876727],
        [0.26242497, 0.6507805 , 0.25735803],
        [0.86561795, 0.30855982, 0.57143946]],

       [[0.37147759, 0.02980467, 0.29478947],
        [0.84386956, 0.92383741, 0.54830527],
        [0.87745356, 0.74107616, 0.66880761]]])